server:
  port: 8080
spring:
  application:
    name: TaskFlow

  datasource:
    url: jdbc:postgresql://localhost:5432/taskflowdb
    username: timalikov
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
    enabled: true