server:
  port: 8080
spring:
  application:
    name: TaskFlow

  datasource:
    url: jdbc:postgresql://localhost:5432/taskflowdb
    username: timalikov
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

  flyway:
    baseline-on-migrate: true
    enabled: true

  data:
    mongodb:
      uri: mongodb+srv://temir:1234@cluster88501.flmcqdz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster88501
      host: localhost
      port: 27017
      database: taskflow_mongodb

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

