spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    mongodb:
      uri: mongodb+srv://temir:1234@cluster88501.flmcqdz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster88501

  h2:
    console:
      enabled: true
